DROP TABLE IF EXISTS people;
CREATE TABLE IF NOT EXISTS people
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username         CHARACTER VARYING(100)                  NOT NULL,
    password         CHARACTER VARYING(100)                  NOT NULL,
    date_of_birthday CHARACTER VARYING(100)                  NOT NULL,
    role             CHARACTER VARYING(100)                  NOT NULL,
    CONSTRAINT person_pk PRIMARY KEY (id)
);

select * from people;
