DROP TABLE people;
CREATE TABLE people
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username         CHARACTER VARYING(100)                  NOT NULL,
    password         CHARACTER VARYING(100)                  NOT NULL,
    date_of_birthday CHARACTER VARYING(100)                  NOT NULL,
    CONSTRAINT person_pk PRIMARY KEY (id)
);

INSERT INTO people(username, password, date_of_birthday)
VALUES ('user', 'user', now()),
       ('admin', 'admin', now());
